ALTER TABLE trips
  ADD COLUMN IF NOT EXISTS outside_temperature_c SMALLINT NULL,
  ADD COLUMN IF NOT EXISTS wind_speed_kmh SMALLINT NULL,
  ADD COLUMN IF NOT EXISTS road_condition VARCHAR(100) NULL;
